setup: add version check.
Before:

    setup.py:40: Warning: 'with' will become a reserved keyword in Python 2.6
    ...
    SyntaxError: invalid syntax

After:

    RuntimeError: Python >= 2.6 is required