doc/conf: use io.open().
Fixes:

    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 497: ordinal not in range(128)

when LC_ALL=C is set.